### PR TITLE
Filter status and filter field

### PR DESCRIPTION
**Pull request by karynas**

### CODE REVIEW

**Comment by Thealoner** [comment]
@yaroslavnikiforov  Please check the styles. The calendar arrows have been changed after one of your commits.
Before:
was
After:
now

**Comment by yaroslavnikiforov** [comment]
[Unsaved changes and entities menu click](https://trello.com/c/j1oxJmwS/301-unsaved-changes-and-entities-menu-click)

**Comment by yaroslavnikiforov** [comment]
[Filter status](https://trello.com/c/C7gGj4ke/280-filter-status)

**Comment by yaroslavnikiforov** [comment]
[Filter field](https://trello.com/c/Dbh76NKm/281-filter-field)

**Comment by yaroslavnikiforov** [comment]
[Adaptive layout](https://trello.com/c/d1jtzJOA/268-adaptive-layout)

**Comment by yaroslavnikiforov** [comment]
[Cursor pointer for menu in left corner](https://trello.com/c/LFhSXXUe/317-cursor-pointer-for-menu-in-left-corner)

**Comment by yaroslavnikiforov** [comment]
[Add checkbox near filter fields for partial or exact search](https://trello.com/c/bxU7LM3M/320-add-checkbox-near-filter-fields-for-partial-or-exact-search)

**Comment by Thealoner** [comment]
Merging this. All unresolved issues go to a new task
https://trello.com/c/tXKoP4AU/283-filter-fixes-move-state-to-redux

**Pull request merged**
